webtalk_init -webtalk_dir /afs/ee.cooper.edu/user/h/halil.turan/Documents/ECE311/hw3/ripple_adder/ripple_adder.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep 27 21:10:42 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d48822b6-63a7-4c21-b020-d76cfbc2860e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bb297fbd-75b6-4458-a771-abed88df9f84" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 10 (buster)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4197.480 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key chain -value "0000400023727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0000400023727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0000400023727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0000400023727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Zed/15000000:" -context "labtool\\usage"
webtalk_transmit -clientid 1614912302 -regid "" -xml /afs/ee.cooper.edu/user/h/halil.turan/Documents/ECE311/hw3/ripple_adder/ripple_adder.hw/webtalk/usage_statistics_ext_labtool.xml -html /afs/ee.cooper.edu/user/h/halil.turan/Documents/ECE311/hw3/ripple_adder/ripple_adder.hw/webtalk/usage_statistics_ext_labtool.html -wdm /afs/ee.cooper.edu/user/h/halil.turan/Documents/ECE311/hw3/ripple_adder/ripple_adder.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
